name: wat_mobile
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.0.2
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.8
  riverpod: ^2.0.2
  intl: ^0.18.1
  hooks_riverpod: ^2.4.6
  flutter_screenutil: ^5.9.0
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  flutter_dotenv: ^5.1.0
  stacked_services: ^1.3.0
  stacked: ^3.4.1+1
  riverpod_annotation: ^2.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  animations: ^2.0.8
  faker: ^2.1.0
  overlay_support: ^2.1.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  stacked_generator: ^1.5.1
  custom_lint: ^0.5.6

flutter:

  uses-material-design: true

  assets:
    - .env
    - .env.staging
    - assets/pngs/
    - assets/svgs/
    - assets/json/

# analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint